import React from "react";

const sizeClasses = {
  txtPoppinsMedium20Gray600: "font-medium font-poppins",
  txtInterBold16WhiteA70001: "font-bold font-inter",
  txtInterMedium16Gray600: "font-inter font-medium",
  txtInterRegular20: "font-inter font-normal",
  txtPoppinsMedium72: "font-medium font-poppins",
  txtInterSemiBold26: "font-inter font-semibold",
  txtInterSemiBold14Gray90002: "font-inter font-semibold",
  txtInterRegular12WhiteA700: "font-inter font-normal",
  txtInterSemiBold14Gray90001: "font-inter font-semibold",
  txtInterSemiBold14Gray600: "font-inter font-semibold",
  txtInterSemiBold16Gray600: "font-inter font-semibold",
  txtInterRegular16Gray90001: "font-inter font-normal",
  txtInterRegular16Gray90002: "font-inter font-normal",
  txtPoppinsSemiBold12: "font-poppins font-semibold",
  txtInterRegular22: "font-inter font-normal",
  txtInterSemiBold20Black900: "font-inter font-semibold",
  txtInterRegular26: "font-inter font-normal",
  txtSpaceGroteskMedium14Gray600: "font-medium font-spacegrotesk",
  txtInterBold12Gray600: "font-bold font-inter",
  txtPoppinsMedium40Black900: "font-medium font-poppins",
  txtPoppinsRegular14: "font-normal font-poppins",
  txtInterRegular14WhiteA70001: "font-inter font-normal",
  txtInterRegular12Gray600_1: "font-inter font-normal italic",
  txtInterRegular12: "font-inter font-normal",
  txtInterRegular14: "font-inter font-normal",
  txtInterRegular16Gray800: "font-inter font-normal",
  txtInterRegular16: "font-inter font-normal",
  txtInterRegular18: "font-inter font-normal",
  txtPoppinsMedium40WhiteA70001: "font-medium font-poppins",
  txtPoppinsMedium20WhiteA70001: "font-medium font-poppins",
  txtInterRegular14Black900: "font-inter font-normal",
  txtInterMedium16WhiteA700: "font-inter font-medium",
  txtInterSemiBold48: "font-inter font-semibold",
  txtPoppinsRegular12Gray90002: "font-normal font-poppins",
  txtBeVietnamProSemiBold48: "font-bevietnampro font-semibold",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtInterBold16WhiteA700: "font-bold font-inter",
  txtPoppinsMedium54: "font-medium font-poppins",
  txtInterBold16Gray600: "font-bold font-inter",
  txtInterSemiBold18Gray90001: "font-inter font-semibold",
  txtInterRegular14WhiteA700: "font-inter font-normal",
  txtInterSemiBold22Bluegray80001: "font-inter font-semibold",
  txtInterSemiBold16Gray50: "font-inter font-semibold",
  txtInterSemiBold16Black900: "font-inter font-semibold",
  txtInterRegular16WhiteA700: "font-inter font-normal",
  txtInterSemiBold14WhiteA700: "font-inter font-semibold",
  txtPoppinsMedium72WhiteA70001: "font-medium font-poppins",
  txtPoppinsMedium28Gray600: "font-medium font-poppins",
  txtPoppinsMedium40: "font-medium font-poppins",
  txtSpaceGroteskMedium14: "font-medium font-spacegrotesk",
  txtInterRegular16Gray600: "font-inter font-normal",
  txtPoppinsMedium72Gray90002: "font-medium font-poppins",
  txtInterSemiBold20Gray90001: "font-inter font-semibold",
  txtInterSemiBold20Gray90002: "font-inter font-semibold",
  txtPoppinsMedium20Gray90002: "font-medium font-poppins",
  txtPoppinsMedium96Black900: "font-medium font-poppins",
  txtPoppinsMedium20Gray90004: "font-medium font-poppins",
  txtInterBold26: "font-bold font-inter",
  txtInterMedium22: "font-inter font-medium",
  txtInterSemiBold16Bluegray200: "font-inter font-semibold",
  txtInterBold22: "font-bold font-inter",
  txtInterRegular20WhiteA70001: "font-inter font-normal",
  txtInterMedium26: "font-inter font-medium",
  txtPoppinsMedium54Gray90002: "font-medium font-poppins",
  txtPoppinsMedium34: "font-medium font-poppins",
  txtInterBold20: "font-bold font-inter",
  txtPoppinsSemiBold54: "font-poppins font-semibold",
  txtInterSemiBold14Bluegray900: "font-inter font-semibold",
  txtInterMedium18: "font-inter font-medium",
  txtInterSemiBold16Gray90001: "font-inter font-semibold",
  txtInterBold18: "font-bold font-inter",
  txtInterSemiBold16Gray90002: "font-inter font-semibold",
  txtInterSemiBold14Gray60001: "font-inter font-semibold",
  txtInterRegular18Gray90002: "font-inter font-normal",
  txtInterSemiBold16Gray90004: "font-inter font-semibold",
  txtInterRegular18Gray90001: "font-inter font-normal",
  txtInterBold12Black900: "font-bold font-inter",
  txtInterBold14: "font-bold font-inter",
  txtInterRegular12Gray90002: "font-inter font-normal",
  txtInterBold16: "font-bold font-inter",
  txtPoppinsMedium16Gray90002: "font-medium font-poppins",
  txtInterMedium16: "font-inter font-medium",
  txtInterBold12: "font-bold font-inter",
  txtInterMedium14: "font-inter font-medium",
  txtInterRegular20Black900: "font-inter font-normal",
  txtInterSemiBold16Teal400: "font-inter font-semibold",
  txtPoppinsMedium24: "font-medium font-poppins",
  txtPoppinsMedium20: "font-medium font-poppins",
  txtInterMedium20: "font-inter font-medium",
  txtPoppinsMedium24WhiteA700: "font-medium font-poppins",
  txtInterBold12WhiteA700: "font-bold font-inter",
  txtInterRegular14Gray600: "font-inter font-normal",
  txtInterRegular12Gray600: "font-inter font-normal",
  txtPoppinsMedium28: "font-medium font-poppins",
  txtPoppinsMedium40Gray90002: "font-medium font-poppins",
  txtPoppinsMedium40Gray90004: "font-medium font-poppins",
  txtPoppinsMedium20Black900: "font-medium font-poppins",
  txtInterSemiBold16Bluegray20001: "font-inter font-semibold",
  txtInterRegular14Gray90002: "font-inter font-normal",
  txtInterBold16BlueA400: "font-bold font-inter",
  txtInterBold16Gray90001: "font-bold font-inter",
  txtInterBold16Teal400: "font-bold font-inter",
  txtInterBold16Gray90002: "font-bold font-inter",
  txtPoppinsMedium34Gray90002: "font-medium font-poppins",
  txtInterRegular20Gray90001: "font-inter font-normal",
  txtInterRegular20Gray90002: "font-inter font-normal",
  txtPoppinsMedium28Gray90004: "font-medium font-poppins",
  txtPoppinsMedium54Black900: "font-medium font-poppins",
  txtInterMedium16Gray90002: "font-inter font-medium",
  txtInterMedium14Gray700: "font-inter font-medium",
  txtInterSemiBold12Gray90004: "font-inter font-semibold",
  txtPoppinsMedium96: "font-medium font-poppins",
  txtInterRegular16Black900: "font-inter font-normal",
  txtInterRegular14Bluegray50: "font-inter font-normal",
  txtInterSemiBold12Gray90001: "font-inter font-semibold",
  txtPoppinsMedium16: "font-medium font-poppins",
  txtInterMedium18Gray60001: "font-inter font-medium",
  txtInterMedium14Gray90002: "font-inter font-medium",
  txtPoppinsMedium28Black900: "font-medium font-poppins",
  txtInterSemiBold14: "font-inter font-semibold",
  txtPoppinsMedium80: "font-medium font-poppins",
  txtInterSemiBold12: "font-inter font-semibold",
  txtInterSemiBold18: "font-inter font-semibold",
  txtInterSemiBold16: "font-inter font-semibold",
  txtInterSemiBold22: "font-inter font-semibold",
  txtInterSemiBold20: "font-inter font-semibold",
} as const;

export type TextProps = Partial<{
  className: string;
  size: keyof typeof sizeClasses;
  as: any;
}> &
  React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLSpanElement>,
    HTMLSpanElement
  >;

const Text: React.FC<React.PropsWithChildren<TextProps>> = ({
  children,
  className = "",
  size,
  as,
  ...restProps
}) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
