import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/welcomethree">WelcomeThree</Link>
        </li>
        <li>
          <Link to="/quickchangelighttypography">
            QuickChangeLightTypography
          </Link>
        </li>
        <li>
          <Link to="/colorlibrary">ColorLibrary</Link>
        </li>
        <li>
          <Link to="/icons">Icons</Link>
        </li>
        <li>
          <Link to="/signuppopupdesktop">SignUpPopupDesktop</Link>
        </li>
        <li>
          <Link to="/homepageone">HomepageOne</Link>
        </li>
        <li>
          <Link to="/homepagetwo">HomepageTwo</Link>
        </li>
        <li>
          <Link to="/homepagethree">HomepageThree</Link>
        </li>
        <li>
          <Link to="/homepagefour">HomepageFour</Link>
        </li>
        <li>
          <Link to="/updatethree">UpdateThree</Link>
        </li>
        <li>
          <Link to="/signinpopupdesktop">SignInPopupDesktop</Link>
        </li>
        <li>
          <Link to="/flyoutcart">FlyoutCart</Link>
        </li>
        <li>
          <Link to="/productpageone">ProductPageOne</Link>
        </li>
        <li>
          <Link to="/productpagetwo">ProductPageTwo</Link>
        </li>
        <li>
          <Link to="/updatetwo">UpdateTwo</Link>
        </li>
        <li>
          <Link to="/shoppageone">ShopPageOne</Link>
        </li>
        <li>
          <Link to="/shoppagetwo">ShopPageTwo</Link>
        </li>
        <li>
          <Link to="/shoppagethree">ShopPageThree</Link>
        </li>
        <li>
          <Link to="/checkout">CheckOut</Link>
        </li>
        <li>
          <Link to="/ordercomplete">OrderComplete</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/myaccount">MyAccount</Link>
        </li>
        <li>
          <Link to="/myaccountaddress">MyAccountAddress</Link>
        </li>
        <li>
          <Link to="/myaccountorders">MyAccountorders</Link>
        </li>
        <li>
          <Link to="/myaccountwishlist">MyAccountwishlist</Link>
        </li>
        <li>
          <Link to="/blogone">BlogOne</Link>
        </li>
        <li>
          <Link to="/blogpostone">BlogPostOne</Link>
        </li>
        <li>
          <Link to="/updateone">UpdateOne</Link>
        </li>
        <li>
          <Link to="/contactusone">ContactUsOne</Link>
        </li>
        <li>
          <Link to="/update">Update</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
